# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "hello.baml": "generator target {\n  output_type \"python/pydantic\"\n  output_dir \"../baml_client\"\n  version \"0.225.0\"\n  default_client_mode sync\n}\n\nfunction Hello(message: string) -> string {\n  client \"openai/gpt-4o-mini\"\n  prompt #\"\n    {{ _.role(\"user\") }}\n    {{ message }}\n  \"#\n}\n",
}

def get_baml_files():
    return _file_map